### ISSUE TITLE
Firestore screenshots or exported json needed for running the project without null error

### ISSUE THREAD

**Issue by scorchy38** [takiuddin93/ChatApp#8]
The common error everyone is facing is because I think it is trying to fetch something from database and since we have a new database with no collections, null error is there, can you please provide your firebase firestore database screenshots, or you can export it in json format using [this](https://github.com/davr59/firestore-json-export-import) and share it here somewhere?

**Comment by Sathyavrv** [comment]
<img width="1425" alt="Screenshot 2021-04-28 at 6 12 15 PM" src="https://user-images.githubusercontent.com/22270298/116405681-87d89b80-a84d-11eb-80fd-f4b8795fdf49.png">
<img width="385" alt="Screenshot 2021-04-28 at 6 17 07 PM" src="https://user-images.githubusercontent.com/22270298/116406221-0fbea580-a84e-11eb-89cf-58d9873a1d56.png">
when I'm logging into google account it shows like this. How  to resolve this?

**Comment by scorchy38** [comment]
> <img alt="Screenshot 2021-04-28 at 6 12 15 PM" width="1425" src="https://user-images.githubusercontent.com/22270298/116405681-87d89b80-a84d-11eb-80fd-f4b8795fdf49.png">
> 
> <img alt="Screenshot 2021-04-28 at 6 17 07 PM" width="385" src="https://user-images.githubusercontent.com/22270298/116406221-0fbea580-a84e-11eb-89cf-58d9873a1d56.png">
> 
> when I'm logging into google account it shows like this. How to resolve this?

You cannot pretty much do anything, you need a copy of database that the original owner of this repo is using and then only you can run the application without any null errors and that is what I have asked for in this issue but I think the person is inactive since a long time.

**Comment by takiuddin93** [comment]
This issue is due to an out dated firebase dependencies, not related to my(owners) firebase storage. When you add the package name and SHA-1 key to your firebase project, it uses your firebase storage not mine.
